# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  build:
    parameters:
      ruby_version:
        type: string
      
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>

    steps:
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          project: linkeddata
      - samvera/parallel_rspec
workflows:
  version: 2
  ci:
    jobs:
      - build:
          name: "ruby2-4"
          ruby_version: "2.4.9"
      - build:
          name: "ruby2-5"
          ruby_version: "2.5.7"
      - build:
          name: "ruby2-6"
          ruby_version: "2.6.5"
